=== stefems/wally/html/xml/postSummary.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
	xmlns:xs="www.whilefalse.io/XMLSchema"
	targetNamespace="www.whilefalse.io"
	xmlns="www.whilefalse.io">
	<xs:element name="postList">
		<xs:complexType>
			<xs:element name="postSummary" maxOccurs="unbounded">
			  <xs:complexType>
				<xs:sequence>
				  <xs:element name="title" type="xs:string"/>
				  <xs:element name="date" type="xs:date"/>
				  <xs:element name="tags"/>
					<xs:sequence>
						<xs:element name="tag" type="string" maxOccurs="unbounded"/>
					</xs:sequence>
				  <xs:element name="imagePath" type="xs:string" minOccurs="0"/>
				  <xs:element name="summaryText" type="xs:string"/>
				  <xs:element name="url" type="xs:anyURI"/>
				</xs:sequence>
			  </xs:complexType>
			</xs:element>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== stefems/wally/html/xml/posts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<postList 
	xmlns="www.whilefalse.io"
	xmlns:xsi="www.whilefalse.io/XMLTest"
	xsi:schemaLocation="postSummary.xsd">
	<postSummary>
		<title>Make Your Commits Meaningful with Emojis</title>
		<date>2016-09-25</date>
		<tags>
			<tag>Code</tag>
			<tag>Humor</tag>
		</tags>
		<imagePath>../postImages/emojiSummary.PNG</imagePath>
		<summaryText>Using emojis as shorthand can save time, be informative, and still be funny.</summaryText>
		<url>EmojisCommit.php</url>
	</postSummary>
	<postSummary>
		<title>Test Post 2</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url>post2.php</url>
	</postSummary>
	<postSummary>
		<title>Test Post 3</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 4</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 5</title>
		<date>2016-09-10</date>
		<tags>
			<tag>Code</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 6</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 7</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 8</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 9</title>
		<date>2016-09-10</date>
		<tags>
			<tag>Code</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 10</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 11</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 12</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 13</title>
		<date>2016-09-10</date>
		<tags>
			<tag>Code</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 14</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 15</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 16</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 17</title>
		<date>2016-09-10</date>
		<tags>
			<tag>Code</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 18</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 19</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
	<postSummary>
		<title>Test Post 20</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
	</postSummary>
</postList>

=== stefems/wally/html/.xml/posts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<postList 
	xmlns="www.whilefalse.io"
	xmlns:xsi="www.whilefalse.io/XMLTest"
	xsi:schemaLocation="postSummary.xsd">
	
	
	<!--
	<postSummary>
		<title>All of the Coding Jargon that No One Explained to You</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
			<tag>Python</tag>
		</tags>
		<summaryText>Confused by init, declare, throw and more? We're gonna help.</summaryText>
		<url>All_of_the_Coding_Jargon_that_No_One_Explained_to_You.php</url>
		<postNumber>3</postNumber>
	</postSummary>
	-->

	<postSummary>
		<title>How I made it: A Twitter Bot that Recommends Bands</title>
		<date>2016-03-14</date>
		<tags>
			<tag>Music</tag>
			<tag>Bots</tag>
			<tag>Twitter</tag>
			<tag>Node</tag>
		</tags>
		<summaryText>Discovering new music can be hard work. I made a Twitter bot to make it a little easier.</summaryText>
		<url>How_I_made_it_A_Twitter_Bot_that_Recommends_Bands.php</url>
		<postNumber>1</postNumber>
	</postSummary>
	<postSummary>
		<title>Twitter Bots: A Curated Collection</title>
		<date>2017-03-13</date>
		<tags>
			<tag>Twitter</tag>
			<tag>Bots</tag>
			<tag>Art</tag>
			<tag>Humor</tag>
		</tags>
		<summaryText>Twitter bots are kinda-sorta the coolest new art form. Take a gander, gain inspiration, and stay woke (yeah, thatâ€™s a bot.)</summaryText>
		<url>Twitter_Bots_A_Curated_Collection.php</url>
		<postNumber>2</postNumber>
	</postSummary>
	<postSummary>
		<title>Learning to Code: Teaching Strategies and Tripping-Blocks</title>
		<date>2017-02-08</date>
		<tags>
			<tag>Coding</tag>
			<tag>Teaching</tag>
			<tag>Learning</tag>
		</tags>
		<imagePath></imagePath>
		<summaryText>Learning to program is hard. This post dives into what makes it hard and what I've learned as a teacher.</summaryText>
		<url>Learning_to_Code_Teaching_Strategies_and_Tripping-Blocks.php</url>
		<postNumber>3</postNumber>
	</postSummary>
	<postSummary>
		<title>Make Your Commits Meaningful with Emojis</title>
		<date>2016-09-25</date>
		<tags>
			<tag>Commits</tag>
			<tag>Emojis</tag>
		</tags>
		<imagePath>../postImages/emojiSummary.PNG</imagePath>
		<summaryText>Using emojis as shorthand can save time, be informative, and still be funny.</summaryText>
		<url>Make_Your_Commits_Meaningful_with_Emojis.php</url>
		<postNumber>4</postNumber>
	</postSummary>
	<!--
	<postSummary>
		<title>All of the Coding Jargon that No One Explained to You</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
			<tag>Python</tag>
		</tags>
		<summaryText>Confused by init, declare, throw and more? We're gonna help.</summaryText>
		<url>All_of_the_Coding_Jargon_that_No_One_Explained_to_You.php</url>
		<postNumber>3</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 4</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Machine-Learning</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>4</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 5</title>
		<date>2016-09-10</date>
		<tags>
			<tag>Video-Games</tag>
			<tag>Java</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
		<postNumber>5</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 6</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
		<postNumber>6</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 7</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>7</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 8</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>8</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 9</title>
		<date>2016-09-10</date>
		<tags>
			<tag>Code</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
		<postNumber>9</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 10</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
		<postNumber>10</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 11</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>11</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 12</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>12</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 13</title>
		<date>2016-09-10</date>
		<tags>
			<tag>Code</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
		<postNumber>13</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 14</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
		<postNumber>14</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 15</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>15</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 16</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>16</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 17</title>
		<date>2016-09-10</date>
		<tags>
			<tag>Code</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
		<postNumber>17</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 18</title>
		<date>2016-09-09</date>
		<tags>
			<tag>Career</tag>
		</tags>
		<imagePath>../postImages/post1Summary.JPG</imagePath>
		<summaryText>p2 text</summaryText>
		<url></url>
		<postNumber>18</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 19</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>19</postNumber>
	</postSummary>
	<postSummary>
		<title>Test Post 20</title>
		<date>2016-09-08</date>
		<tags>
			<tag>Humor</tag>
		</tags>
		<summaryText>p3 text</summaryText>
		<url></url>
		<postNumber>20</postNumber>
	</postSummary>
-->
</postList>
